### PR TITLE
token_unseal: use cgettop

### PR DESCRIPTION
**Pull request by nwf**
Shave two instructions off the fast unsealer.  It's helpful to remember the ISA. :)

### CODE REVIEW

**Review by davidchisnall — APPROVED** [review]
The compiler didn’t support cgettop when this was written!

**Comment by rmn30** [comment]
Just checking: this change means that `ct0` is no longer clobbered. I think that is OK as it contains the user's key which is not secret?

**Comment by davidchisnall** [comment]
We never actually use *c*t0, so we could replace line 60 with a mv / cgetaddr instead of a cmove and just extract the value.  I don't think it makes a different for security, but it means that we are still clobbering the capability (which is not secret), just leaking the integer value (which is also not secret, but conveys no rights by itself).

**Comment by nwf** [comment]
Oh, yea, good call.  Done, and some other cleanups while in the neighborhood; hopefully nothing objectionable.

**Review by davidchisnall — APPROVED** [review]

**Pull request merged**
